---
title: "Newspaper"
output: html_document
date: "2024-04-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
#library(readxl)
library(survminer)
library(patchwork)
library(survival)
employees <- read_csv("Uncleaned_employees_final_dataset (1).csv")

employees$avg_training_score %>% hist()

```

```{r}
employees %>% ggplot(aes(x = avg_training_score)) + geom_boxplot()
```

```{r}
employees$avg_training_score %>% quantile()
```


```{r}
employees <- employees %>% mutate(good = if_else(avg_training_score >= 60, 1, 0))
```

```{r}
employees$length_of_service %>% is.na() %>% sum()
```

```{r}
ajusteSurv <- survfit(Surv(employees$length_of_service, employees$good)~1)
typeof(ajusteSurv)
```

```{r}
ajusteSurv$surv
```
```{r}
tibble(time = ajusteSurv$time, surv = ajusteSurv$surv) %>% ggplot(aes(x = time, y = surv)) + geom_step()
```
```{r}
employees %>% ggplot(aes(x = department)) + geom_bar()
```

```{r}
employees_RD <- employees %>% filter(department == "R&D")
employees_SM <- employees %>% filter(department == "Sales & Marketing")
ajusteSurv_RD <- survfit(Surv(employees_RD$length_of_service, employees_RD$good)~1)
ajusteSurv_SM <- survfit(Surv(employees_SM$length_of_service, employees_SM$good)~1)

tibble(time = ajusteSurv_RD$time, surv = ajusteSurv_RD$surv) %>% ggplot(aes(x = time, y = surv)) + geom_step(color = "forestgreen") + 
  geom_step(color = "deeppink2",data = tibble(time = ajusteSurv_SM$time, surv = ajusteSurv_SM$surv))
```

```{r}
employees_HR <- employees %>% filter(department == "HR")
employees_FI <- employees %>% filter(department == "Finance")
employees_AN <- employees %>% filter(department == "Analytics")
ajusteSurv_HR <- survfit(Surv(employees_HR$length_of_service, employees_HR$good)~1)
ajusteSurv_FI <- survfit(Surv(employees_FI$length_of_service, employees_FI$good)~1)
ajusteSurv_AN <- survfit(Surv(employees_AN$length_of_service, employees_AN$good)~1)

tibble(time = ajusteSurv_HR$time, surv = ajusteSurv_HR$surv) %>% 
  ggplot(aes(x = time, y = surv, fill = "HR")) + geom_step(color = "goldenrod2") + 
  geom_step(color = "darkorchid3",data = tibble(time = ajusteSurv_FI$time, surv = ajusteSurv_FI$surv)) + 
  geom_step(color = "cornflowerblue",data = tibble(time = ajusteSurv_AN$time, surv = ajusteSurv_AN$surv)) + 
  geom_step(color = "deeppink2",data = tibble(time = ajusteSurv_RD$time, surv = ajusteSurv_RD$surv))
```

```{r}
library(RColorBrewer)
library(extrafont)
#font_import()
models_surival_employees <- employees %>% group_by(department) %>% nest() %>% 
  mutate(surv_models = map(data, ~survfit(Surv(.x$length_of_service, .x$good)~1)))

departments <- models_surival_employees$department

colores_departamentos <- c("Technology" = "#1f77b4",     # Azul
                           "HR" = "#ff7f0e",            # Naranja
                           "Sales & Marketing" = "#d62728",  # Rojo
                           "Procurement" = "#2ca02c",   # Verde
                           "Finance" = "#6baed6",       # Azul claro
                           "Analytics" = "#9467bd",     # Morado
                           "Operations" = "#8c564b",    # Marrón
                           "Legal" = "#7f7f7f",         # Gris
                           "R&D" = "#17becf")          # Turquesa

base_plot <- tibble(time = models_surival_employees$surv_models[[1]]$time, 
       surv = models_surival_employees$surv_models[[1]]$surv) %>% 
  ggplot(aes(x = time, y = surv, color = !!departments[[1]])) + geom_step()


for (g in 2:dim(models_surival_employees)[1]){
  department <- departments[[g]]
  base_plot <- base_plot + 
    geom_step(aes(color = !!department),
              data = tibble(time = models_surival_employees$surv_models[[g]]$time, 
                            surv = models_surival_employees$surv_models[[g]]$surv))
}

base_plot + 
  scale_color_manual(values = colores_departamentos) + 
  theme_minimal() + 
  ggtitle("Probability of obtaining a high average training score by department") + 
  labs(x = "Length of service", y = "") + 
  guides(colour=guide_legend(title="Departments:")) + 
  theme(legend.position="bottom", 
        text=element_text(family="Roboto")) +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank())
  #theme(panel.grid.major = element_line(linetype = "blank"),
  #      panel.grid.minor = element_line(linetype = "blank"))
```

```{r}
HRSurv <- tibble(Time = ajusteSurv_HR$time, Surv= ajusteSurv_HR$surv)

HRSurv_risk <- HRSurv %>% # Tomamos los datos
  mutate(Surv_aux = lead(Surv)) %>% # Recorremos la supervivencia para facilitar los cálculos
  mutate(quotien = Surv_aux/Surv) %>% # Hacemos el cociente
  mutate(Risk_rate = 1-quotien) %>% #Obtenemos la tasa de fallo
  head(-1)

HRSurv_risk %>% ggplot(aes(x = Time, y = Risk_rate)) + geom_line()
```

```{r}
ANSurv <- tibble(Time = ajusteSurv_AN$time, Surv= ajusteSurv_AN$surv)

ANSurv_risk <- ANSurv %>% # Tomamos los datos
  mutate(Surv_aux = lead(Surv)) %>% # Recorremos la supervivencia para facilitar los cálculos
  mutate(quotien = Surv_aux/Surv) %>% # Hacemos el cociente
  mutate(Risk_rate = 1-quotien) %>% #Obtenemos la tasa de fallo
  head(-1)

ANSurv_risk %>% ggplot(aes(x = Time, y = Risk_rate)) + geom_line()
```

```{r}
HRSurv_risk$Risk_rate %>% cumsum() %>% 
  as_tibble() %>% # Una buena estructura de datos
  mutate(Time = row_number()) %>% # Añadimos un índice para el tiempo
  dplyr::select(Time, value) %>%  # Para un buen orden
  rename(Time = Time, H = value) %>% ggplot(aes(x =Time, y = H)) + geom_line()
```

```{r}
ANSurv_risk$Risk_rate %>% cumsum() %>% 
  as_tibble() %>% # Una buena estructura de datos
  mutate(Time = row_number()) %>% # Añadimos un índice para el tiempo
  dplyr::select(Time, value) %>%  # Para un buen orden
  rename(Time = Time, H = value) %>% ggplot(aes(x =Time, y = H)) + geom_line()
```

```{r}
summary_survival <- function(time, datos_surv){
  all_surv_sums = sum(datos_surv)
  list("Mean" =  sum(datos_surv), 
       "Var" = 2*sum(time*datos_surv)-sum(datos_surv)^2,
       "Residual_median" = tibble(Time = time, 
                                  cumsum_surv = lag(cumsum(datos_surv)),
                                  mr_2 = rev(cumsum(datos_surv))/datos_surv) %>% 
         mutate(mr = map_dbl(cumsum_surv, ~sum(all_surv_sums, -.x, na.rm = T))))
}

summary_survival(ajusteSurv_HR$time, ajusteSurv_HR$surv)$Residual_median %>% 
  ggplot(aes(x = Time, y = mr)) + geom_line()
```

```{r}
(summary_survival(ajusteSurv_HR$time, ajusteSurv_HR$surv)$Residual_median %>%
  ggplot(aes(x = Time, y = mr)) + geom_line()) + (summary_survival(ajusteSurv_AN$time, ajusteSurv_AN$surv)$Residual_median %>%
  ggplot(aes(x = Time, y = mr)) + geom_line())
```

```{r}
ajusteSurv_AN
```
```{r}
(models_surival_employees %>% filter(department == "Analytics"))$data
```
