---
title: "Walmart"
output: html_document
date: "2024-03-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Pruebas de hipótesis:

+ Estacionariedad, Invertibilidad
  - Dickey-Fuller
    - p < pequeño
  - KPSS
    - p > grande
+ Residuales no correlacionados
  - Ljung-Box
    - p > grande

```{r cars}
library(tidyverse)
walmart <- read_csv("Walmart.csv")
walmart
```

```{r}
walmart %>% summary()
```

```{r}
danna_number <- 31
walmart_31 <- walmart %>% filter(Store == 31) %>% mutate(Date = as.Date(Date,  format = "%d-%m-%Y"))
```

```{r}
ts_walmart_31 <- ts(data = walmart_31$Weekly_Sales, frequency = 52)
ts_walmart_31
```
```{r}
library(forecast)
library(plotly)
ts_walmart_31 %>% autoplot() %>% ggplotly()
```

```{r}
decompose(ts_walmart_31) %>% autoplot()
```

```{r}
library(patchwork)
(Acf(ts_walmart_31) %>% autoplot()) + (Pacf(ts_walmart_31) %>% autoplot())
```

```{r}
ts_walmart_31 %>% nsdiffs()
ts_walmart_31_diffS <- ts_walmart_31 %>% diff(1, lag = 52)
(Acf(ts_walmart_31_diffS) %>% autoplot()) + (Pacf(ts_walmart_31_diffS) %>% autoplot())
```

```{r}
ts_walmart_31_diffS_diff <- ts_walmart_31 %>% diff(1, lag = 52) %>% diff()
(Acf(ts_walmart_31_diffS_diff) %>% autoplot()) + (Pacf(ts_walmart_31_diffS_diff) %>% autoplot())
```
```{r}
model_1 <- Arima(ts_walmart_31, order = c(6, 1, 2), seasonal = c(0, 1, 0))
model_1
```

```{r}
ts_walmart_31_log <- ts_walmart_31 %>% log() %>% diff(1, lag = 52) %>% diff()
(Acf(ts_walmart_31_log) %>% autoplot()) + (Pacf(ts_walmart_31_log) %>% autoplot())
```

```{r}
model_2 <- Arima(ts_walmart_31_log, order = c(6, 1, 2), seasonal = c(0, 1, 0))
model_2
```
```{r}
model_3 <- auto.arima(ts_walmart_31)
model_4 <- auto.arima(ts_walmart_31 %>% log())
model_4
```
```{r}
model_2
```
```{r}
forecast::checkresiduals(model_2, plot = F)
```

```{r}
library(urca)
urca::ur.df(model_2$fitted) %>% summary()
```

```{r}
model_4 %>% forecast(h = 30) %>% autoplot()
```

